<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <LangVersion>8.0</LangVersion>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <PteroPanelUrl>https://panel.yourdomain.com</PteroPanelUrl>
    <PteroClientToken>ptlc_your_api_key_here</PteroClientToken>
    <PteroServerID>your_short_id</PteroServerID>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SDG.NetTransport">
      <HintPath>libs\SDG.NetTransport.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>libs\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>libs\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>libs\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rocket.Unturned">
      <HintPath>libs\Rocket.Unturned.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rocket.API">
      <HintPath>libs\Rocket.API.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Rocket.Core">
      <HintPath>libs\Rocket.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&quot;C:\Program Files (x86)\WinSCP\winscp.com&quot; /command ^
      &quot;open $(PteroSFTPURL):$(PteroSFTPPort)/ -username=$(PteroSFTPUser).$(PteroServerID) -password=$(PteroSFTPPass) -hostkey=*&quot; ^
      &quot;put &quot;&quot;$(TargetPath)&quot;&quot; Servers/unturned/Rocket/Plugins/&quot; ^
      &quot;exit&quot;" />
  </Target>

</Project>